### ISSUE TITLE
No compiled file published to npm in 1.0.7

### ISSUE THREAD

**Issue by ZZYSonny** [google/web-serial-polyfill#23]
In latest version of polyfill, the whole repo is uploaded to npm. There is no compiled js file or dist folder. But `package.json` still requires js files inside dist folder. As a result, I am unable to import serial.

File structure node_modules/web-serial-polyfill in 1.0.7
![image](https://user-images.githubusercontent.com/28442838/112741886-f959cb80-8fbb-11eb-9c16-00ad2b3eaa1d.png)
file structure in 1.0.6
![image](https://user-images.githubusercontent.com/28442838/112741873-e0e9b100-8fbb-11eb-84ce-299101378283.png)

**Comment by Jack-Rogers** [comment]
For anyone wanting to compile to JS
1. Install Typescript `npm i -g typescript`
2. CD to the `web-serial-polyfill` folder `cd node_modules/web-serial-polyfill`
3. Compile `tsc -d`
4. Find the JS files in `dist`

**Comment by reillyeon** [comment]
James, can you upload a new version with the build artifacts in place?

**Comment by jameshollyergoogle** [comment]
Uploaded.

**Comment by ZZYSonny** [comment]
Same problem in 1.0.8

**Comment by jameshollyergoogle** [comment]
My mistake. Dist folder should be included in 1.0.9.

**Comment by ZZYSonny** [comment]
Still no dist folder in 1.0.9

**Comment by reillyeon** [comment]
It looks like the issue is that `dist/` is specified in the `.gitignore` file in the repo. `npm publish` will ignore files in `.gitignore` when packaging and so it doesn't package this directory. You should be able to use `npm publish --dry-run` to see what files have been packaged without actually uploading a new version to npm. From the documentation it seems like we want to add a "files" list to `package.json` and/or create a separate `.npmignore` file to specifically control packaging.

See https://docs.npmjs.com/cli/v7/commands/npm-publish for more details.

**Comment by jameshollyergoogle** [comment]
.npmignore file added. Sorry for all this trouble. Hopefully it is all working properly in 1.0.10. I created a new project and npm installed and I got the dist folder. If your experience is different please post back in here.
