### ISSUE TITLE
add optional parameter signalOptions to open

### ISSUE THREAD

**Issue by A-J-Bauer** [google/web-serial-polyfill#30]
Background: When opening the serial port on some development devices e.g. Arduino, the device gets reset if DTR is true.
It would be really nice to be able to connect and see periodic serial output of possibly long running programms without the controller restarting when opening the serial port.

The default setting of dataTerminalReady in the open function should be optionally changeable somehow.

Proposal:
```javascript
    /**
     * a function that opens the device and claims all interfaces needed to
     * control and communicate to and from the serial device
     * @param {SerialOptions} options Object containing serial options
     * @param {SignalOptions} optional signals Object containing signal options
     * @return {Promise<void>} A promise that will resolve when device is ready
     * for communication
     */
    async open(options, signals) {
        this.serialOptions_ = options;
        this.signalOptions_ = signals !== undefined ? signals : { dataTerminalReady: true }
        this.validateOptions();
        try {
            await this.device_.open();
            if (this.device_.configuration === null) {
                await this.device_.selectConfiguration(1);
            }
            await this.device_.claimInterface(this.controlInterface_.interfaceNumber);
            if (this.controlInterface_ !== this.transferInterface_) {
                await this.device_.claimInterface(this.transferInterface_.interfaceNumber);                
            }
            await this.setLineCoding();
            await this.setSignals(this.signalOptions_);
        }
        catch (error) {
            if (this.device_.opened) {
                await this.device_.close();
            }
            throw new Error('Error setting up device: ' + error.toString());
        }
    }
```
This would also be nice in the existing component:Blink>Serial but I don't know how to make a feature request there.

**Comment by reillyeon** [comment]
As I explained in my response to the [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1198181) you filed, from my research the serial port drivers included with most operating systems automatically assert the DTR signal when the port is opened by an application and release it when the port is closed. The behavior of this polyfill library, since it attempts to duplicate what both the browser and operating system do, is to do the same. However unlike in Chromium, since this library is taking over the role of the USB device driver, it can choose to work differently.

This needs to be done carefully to avoid deviating too much from the interface specified by the [Web Serial API](https://wicg.github.io/serial). The best option seems to be to extend the SerialPolyfillOptions dictionary that is passed to requestPort() to include an option for controlling this behavior.

**Comment by A-J-Bauer** [comment]
Yes you are right, after digging into this some more and writing some native programs for Windows and Debian I found out that I can only make this work after the arduino's port was opened at least once (resetting on first open) without unplugging which defeats the hole point.  So scrap, but it was worth a try. Knowing that it just behaves this way is not necessarily a bad thing after all.  Thank you for the inisghts and these great projects you are working on (serial>blink and polyfill) :sunglasses:. I think the possibilites of this combined with pwa are really great.
